FROM php:7.4-fpm
MAINTAINER me <surg.ru@gmail.com>
RUN apt-get update && apt-get install -y \
        curl \
        wget \
        git \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libpng-dev \
        libzip-dev \
        zip \
        unzip \
        mc \
        libicu-dev \
        icu-devtools \
    && docker-php-ext-install -j$(nproc) iconv  mysqli pdo_mysql zip \
    && docker-php-ext-configure intl \
    && docker-php-ext-install intl \
    && docker-php-ext-configure gd --with-freetype=/usr/include/ --with-jpeg=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd
     RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
     ADD php.ini /usr/local/etc/php/conf.d/40-custom.ini
     WORKDIR /var/www
     CMD ["php-fpm"]
